### ISSUE TITLE
Failed to resolve: com.github.ganfra:material-spinner:2.0.0

### ISSUE THREAD

**Issue by AliYusuf95** [ganfra/MaterialSpinner#105]
When I try to import the library it's give me this error
`Error:(86, 14) Failed to resolve: com.github.ganfra:material-spinner:2.0.0`
Even when I try to use version 1.1.2 I have same error, but 1.1.1 it's works fine.

**Comment by hiepbeos** [comment]
i have same problem
Error:Could not GET 'https://jitpack.io/com/github/ganfra/material-spinner/2.0.0/material-spinner-2.0.0.pom'. Received status code 401 from server: Unauthorized

**Comment by ganfra** [comment]
Hey, yeah, the release has not been pushed to maven yet.
It'll be ok very soon.
