### ISSUE TITLE
android:entries is not working.

### ISSUE THREAD

**Issue by diofeher** [ganfra/MaterialSpinner#14]
android:entries is not working. It shows only the name at "hint" option.

**Comment by vj-1023** [comment]
same problem.
Only hint displayed

**Comment by ganfra** [comment]
Sorry for the very late answer ... I can't reproduce your error, could you provide me your exact xml ?

**Comment by asinel** [comment]
When I use "entries", it shows hint 2 times

**Comment by mdumrauf** [comment]
I am getting the same error as @asinel

**Comment by mdumrauf** [comment]
Fixed in #49
