### ISSUE TITLE
How to change title color?

### ISSUE THREAD

**Issue by SwaXTech** [ganfra/MaterialSpinner#142]
Using 'app:ms_baseColor="@android:color/white" '
the color of the bottom line is changed, but also the color of the pop up title is changed

app:ms_dropDownHintView not working for me

![image](https://user-images.githubusercontent.com/43499966/50568346-2c567b80-0d2f-11e9-9c03-ca5d1b0aadad.png)

![image](https://user-images.githubusercontent.com/43499966/50568347-38423d80-0d2f-11e9-947e-e9932828ae3e.png)

![image](https://user-images.githubusercontent.com/43499966/50568352-46905980-0d2f-11e9-917e-5e4288a3fa9f.png)

![image](https://user-images.githubusercontent.com/43499966/50568358-5f990a80-0d2f-11e9-9cad-13a48442f7ca.png)

**Comment by Chivorns** [comment]
Hi you can try to check this library: https://github.com/Chivorns/SmartMaterialSpinner.
Hope it can help what you need
