### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by billy9222** [ganfra/MaterialSpinner#143]
Floating text doesn't animate when creating view programmatically, It doesn't animate floating label rather give a jerk. What is the thing that I am missing. I am attaching file please have a look.
Thank you
[mobizen_20190131_151037.zip](https://github.com/ganfra/MaterialSpinner/files/2816664/mobizen_20190131_151037.zip)

**Comment by gigaga** [comment]
Same issue :(
Did u find a workaround?

**Comment by billy9222** [comment]
> Same issue :(
> Did u find a workaround?

I guess programmatically it doesn't animate because of some attribute set that are not being set. Instead of creating it in code, inflate the view via inflater.

**Comment by gigaga** [comment]
@billy9222 ok. I use this programmatically like you. For my part, I fixed it directly in the code of MaterialSpinner class.

**Comment by billy9222** [comment]
How can you please share which part did you change in the class to make it work?

**Comment by gigaga** [comment]
@billy9222, of course! In MaterialSpinner code

```java
    @Override
    public void onAnimationUpdate(ValueAnimator animation) {
        invalidate();
    }
```java

becomes

```java
    @Override
    public void onAnimationUpdate(ValueAnimator animation) {
        floatingLabelPercent =  (Float)animation.getAnimatedValue();
        invalidate();
    }
```java

**Comment by billy9222** [comment]
@gigaga  thank you :)  This was really bothering from a very long time.
