### ISSUE TITLE
Dropdown Arrow is shown below line when no entries

### ISSUE THREAD

**Issue by SangeetaSoni** [ganfra/MaterialSpinner#15]
Hi @ganfra 

The dropdown arrow appears below the line when no entries are present in it. It is shown above the line only when there are entries available.
![device-2015-05-22-093750](https://cloud.githubusercontent.com/assets/6103983/7764049/216d6f12-0068-11e5-8d28-354bf948e4f8.png)
![device-2015-05-22-093923](https://cloud.githubusercontent.com/assets/6103983/7764047/20308742-0068-11e5-86a2-9ac2fe67ef6f.png)

**Comment by ganfra** [comment]
thanks for this issue, I'll look into it as soon as possible !

**Comment by LOG-TAG** [comment]
is there any ways to disable under line ? thinking of using it on Toolbar to get out of all this spinner bugs !!  http://stackoverflow.com/questions/26755878/how-can-i-fix-the-spinner-style-for-android-4-x-placed-on-top-of-the-toolbar

**Comment by mdumrauf** [comment]
This is working as expected. Please check the example introduced recently.
