### ISSUE TITLE
Extra space

### ISSUE THREAD

**Issue by ondroEd** [ganfra/MaterialSpinner#2]
There are huge extra spaces above and below of spinner in Android 4.1.1

**Comment by ganfra** [comment]
With the hint and the error message printed ?

**Comment by ondroEd** [comment]
Here is how it looks at Genymotion (Google Nexus S 4.1.1 API 16)
![material_spinner_api16](https://cloud.githubusercontent.com/assets/5443140/7509146/2f01a652-f4a6-11e4-94ce-baa58eb6a953.gif)

**Comment by ganfra** [comment]
Ok, thanks for your issue ! I'll correct it as soon as possible

**Comment by levisaturnino** [comment]
I'm having the same problem. Any solution to this problem?

**Comment by drindt** [comment]
I'm having the same problem. Just written here to get notified if something changes here. Thank you!

**Comment by Daan-Hoogland** [comment]
+1, does anyone have a temp solution for this yet?

**Comment by ganfra** [comment]
I'll update the lib at the end of the week

**Comment by rocboronat** [comment]
Wep @ganfra I think that I resolved this issue, and it was included in the PR :·D

**Comment by ganfra** [comment]
Fixed on 1.1.0 !
