### ISSUE TITLE
mapping 2 items from db

### ISSUE THREAD

**Issue by mehdi-salehi** [ganfra/MaterialSpinner#24]
how can i map 2 db item in your spinner like this:
 private static final String[] FROM = {
            PropertyContract.Column.item1,
            PropertyContract.Column.item2
    }; //
    private static final int[] TO = {
            R.id.file_list_row_i1,
            R.id.file_list_row_i2
    };

I try bindView but null pointer raiseddddddddd:(

**Comment by ganfra** [comment]
bindView is a method from CursorAdapter not BaseAdapter (the one my adapter inherite)
