### ISSUE TITLE
ListView of MaterialSpinners --> selection getting forgotten

### ISSUE THREAD

**Issue by dhrushilbadani** [ganfra/MaterialSpinner#27]
I'm creating a ListView of MaterialSpinners. If I select something in one spinner, and then scroll down, and go back up, that spinner's selection is lost. How do I make the spinner remember its selection?
Thanks :)

**Comment by ganfra** [comment]
Sorry for the late ! Is it something which works with the normal spinner ???

**Comment by dhrushilbadani** [comment]
I am not very sure about that, I fixed it though, by caching the user selections using a HashMap! Thanks ganfra! It's a really slick library otherwise.

**Comment by ganfra** [comment]
Ok nice :)
