### ISSUE TITLE
setSelection is not working

### ISSUE THREAD

**Issue by josephmason** [ganfra/MaterialSpinner#28]
Materialspinner.setSelection(Index) is not working with this library

**Comment by roygwsidev** [comment]
hi,
try this
spinner.post(new Runnable() {
            @Override
            public void run() {
           spinner.setSelection(index);
            }
        });

**Comment by josephmason** [comment]
hi roygwsidev,
this worked for me
thanks

**Comment by ganfra** [comment]
Thanks for the answer :)
