### ISSUE TITLE
Can we remove padding in spinner

### ISSUE THREAD

**Issue by ahmadplero** [ganfra/MaterialSpinner#30]
Please tell me how to remove padding withing spinner.

**Comment by ganfra** [comment]
Do you mean the floating label and error paddings ?

**Comment by zhenikk** [comment]
I have a similar problem. I guess the author mean the padding of hint. 
![1444712703776](https://cloud.githubusercontent.com/assets/9072144/10445883/2545490e-7181-11e5-9252-c972a771c2cb.jpg)

**Comment by ganfra** [comment]
This is the pre allocated space for the floating label ...

**Comment by crestf** [comment]
I also want to modify the padding (especially the hint) because the space is slightly different with original Text Input Layout. Just want to make consistency between components. Is it possible?

**Comment by arok** [comment]
Just override default styles for spinner items in your application theme.
See the attribute android:spinnerItemStyle

**Comment by kodeo** [comment]
It's possible to realign the floating label using either `app:ms_alignLabels="false"` or `<dimen name="right_left_spinner_padding">0dp</dimen>`, but I can't find any way at all of having the initial unselected text aligned flush left with the selected text. Surely this should be the default behaviour?

@arok, I've looked into your suggestion of using `android:spinnerItemStyle` to achieve this, but with no joy. Are you able to elaborate further? Thanks.

**Comment by petecocoon** [comment]
Hi see this pull request https://github.com/ganfra/MaterialSpinner/pull/64

**Comment by mdumrauf** [comment]
Closing as it was fixed in #64

**Comment by lxkwh** [comment]
> I also want to modify the padding (especially the hint) because the space is slightly different with original Text Input Layout. Just want to make consistency between components. Is it possible?

I meet the same problem！
