### ISSUE TITLE
Selector y-position too high when Floating Text visible

### ISSUE THREAD

**Issue by Gautham** [ganfra/MaterialSpinner#34]
When the floating text is displayed after selecting an item, the Selector should ideally be moved a bit down. Currently, it appears way too high up.

```
    drawSelector(canvas, getWidth() - rightLeftSpinnerPadding, getPaddingTop() + dpToPx(8));
```

I think you should change dpToPx(8) to be measured from the FloatingText itself.

I am a bit tied up right now else Id have tried to fix it myself and send you a PR :( Anyway, this is a great library otherwise so Thanks for all the hard work!

**Comment by ganfra** [comment]
I don't get it, I've never seen the selector moving in any app ?

**Comment by cody1024d** [comment]
I'm seeing this as well.  Basically, when I have a hint set up, and then select an item, the selector arrow's position gets translated up, where it actually displays ABOVE the selected item, and actually in between the label and the item itself

**Comment by RaghuManickam** [comment]
yes i too have the same issue . can u help me to fix this issue soon
![bug](https://cloud.githubusercontent.com/assets/12092816/13102389/f4fe52a2-d573-11e5-923d-01b08c8cc765.png)

**Comment by mdumrauf** [comment]
This doesn't seem to be happening in current version. Closing. Please re-open if you consider this is a bug in 1.1.1.
