### ISSUE TITLE
How can i disable the floating hint

### ISSUE THREAD

**Issue by thundenilla** [ganfra/MaterialSpinner#36]
How can i disable the floating hint, but still have the hint for the spinner (editText) look and feel. Thank you

**Comment by ganfra** [comment]
not really possible right now ... to override this, you could set an empty floating_label text.

**Comment by thundenilla** [comment]
well i already set it empty, but still. after you done choosing the input or item. it still show up. just in  a blink!

**Comment by Emeritus-DarranKelinske** [comment]
Did you find a solution for this?
