### ISSUE TITLE
Material style

### ISSUE THREAD

**Issue by DoruAdryan** [ganfra/MaterialSpinner#37]
Regarding material style, IMHO, extending AppCompatSpinner would add more value to this library.
Also, I think it would be better to have the paddings / spacings as described in [here](http://www.google.ro/design/spec/components/text-fields.html#text-fields-floating-labels).
Thanks for your effort in creating this library!

**Comment by mdumrauf** [comment]
Thanks! Already extending `AppCompatSpinner`. Feel free to open a new issue if you need it.
