### ISSUE TITLE
Issue with the Adapter Type Count when app:ms_hint is set

### ISSUE THREAD

**Issue by rocboronat** [ganfra/MaterialSpinner#4]
If the `app:ms_hint` attribute is set, the app launch this Exception:
`java.lang.IllegalArgumentException: Spinner adapter view type count must be 1`

BTW, in addition, our Adapter overrides the `getViewTypeCount()`(in a way to solve the issue in a desesperated way :·)

Our definition in the Layout:
```xml
    <fr.ganfra.materialspinner.MaterialSpinner
                android:id="@+id/s_level"
                style="@style/spinner_material"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_marginTop="@dimen/gap_high"
                android:paddingBottom="@dimen/gap_mhigh"
                android:paddingTop="@dimen/gap_mhigh"
                app:ms_hint="test" />
```
The Adapter's great method:
```java
    @Override
    public int getViewTypeCount() {
        return 1;
    }
```

Thanks for your work!

**Comment by ganfra** [comment]
Yes, that's a known issue with adapter on Lollipop ! The correction is coming very soon :)

**Comment by rocboronat** [comment]
Thank you @ganfra :+1: :+1: :+1:

**Comment by rocboronat** [comment]
Solved!
