### ISSUE TITLE
Floating Label Text Size

### ISSUE THREAD

**Issue by kirtich** [ganfra/MaterialSpinner#48]
Hi Team,

Floating Label Text size is not defined , I have tried it but getting error, I have gone through with your code as well but I didnt get any line related to floating label text size as in MAterialEditText.
 <app:met_floatingLabelTextSize="@dimen/floatinglabel_textSize">

Please guide me if I am wrong.

**Comment by marceloquinta** [comment]
Same here

**Comment by eklam** [comment]
You can override the size by providing a dimension value with the name `label_text_size`.

Example:

```xml
<dimen name="label_text_size">24sp</dimen> <!-- Default is 12sp -->
```
