### ISSUE TITLE
The dimens should be setted from layout.xml and programmatically

### ISSUE THREAD

**Issue by rocboronat** [ganfra/MaterialSpinner#5]
We'll fork the whole project only to set the `floating_label_top_spacing`, `floating_label_bottom_spacing` and `floating_label_inside_spacing`.

It would be great if these attributes could be set at layout.xml in a first stage, or programmatically in a second stage.

Thanks for your work!

**Comment by ganfra** [comment]
Alright, I will add this feature on tomorrow :)

**Comment by rocboronat** [comment]
Thank you @ganfra !

What about the left and right margin of the label? (actually, that's my issue, I can't align it with other fields, like EditTexts.

**Comment by rocboronat** [comment]
Wep! Same issue than the dimens, and also with the label: I cannot set the colour of the floatingLabelText. I prefer to add the issue in this issue instead of opening a new one, 'cause it's about the same topic: styling the Widget from layout.xml or a style.xml

Thank you @ganfra !

**Comment by ganfra** [comment]
Instead of adding margin, you can choose to set floating label align or not with attribute "ms_alignLabels" 

For the color, your floatinglabel get the color your set with attribute baseColor ... I don't want to allow changing the color separately from the underline one

**Comment by rocboronat** [comment]
Great, thanks for your answer, @ganfra !

About your decision about the colors, it's a issue. I'm daltonic (so isn't not a big problem for me, lol!), but design people uses to love that kind of possibilities. In our case, they want the label with one tone of gray, and the line of the spinner with another one. So... wai! (what an issue!)

I totally understand that it's not your work to do it, but probably other people needs that detail of implementation.

Hope I made you rethink this point! :·)

About the `ms_alignLabels`: Great!!

**Comment by rocboronat** [comment]
Solved!
