### ISSUE TITLE
Change floating label text size

### ISSUE THREAD

**Issue by Andrew-Quebe** [ganfra/MaterialSpinner#51]
This doesn't seem possible...would be nice if it was!

**Comment by eklam** [comment]
Duplicate: #48

**Comment by Andrew-Quebe** [comment]
@eklam at the time of writing this issue, there wasn't a reply from you on #48 and now there is. Besides, his issue is a bit different: "Floating Label Text size is not defined".

**Comment by eklam** [comment]
Yes, I was trying to do something similar and replied to the issue, sorry for being blunt

**Comment by Andrew-Quebe** [comment]
@eklam no biggie...thanks for the info :)
