### ISSUE TITLE
Incorrect indexing due to hint

### ISSUE THREAD

**Issue by WonderCsabo** [ganfra/MaterialSpinner#59]
If one uses a hint, the the indexing will be shifted by one. This will cause unexpected behaviour:
- `setSelection()` will select wrong items
- when restoring the view state, the spinner will jump to a next item from the selected one

**Comment by filipebezerra** [comment]
Same bug with me

**Comment by mdumrauf** [comment]
This is fixed in #49. I will bump the priority now.
