### ISSUE TITLE
Allow different thickness for normal and error Spinners

### ISSUE THREAD

**Issue by rocboronat** [ganfra/MaterialSpinner#7]
We're creating a huge form using MaterialEditText and MaterialSpinner.

MaterialEditText allows us to have different thickness if an EditText has a normal or an error state. But... MaterialSpinner can't do it.

The first solution I thought were to work with a thickness of 1 in all the cases, but it would be great if MaterialSpinner can differentiate the behaviour. A link to the Android Material guideline: http://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field

Thanks for your work, @ganfra !

**Comment by carlesferrer** [comment]
+1

**Comment by rocboronat** [comment]
Wep! The related PR where I did it :·)

https://github.com/ganfra/MaterialSpinner/pull/11

**Comment by rocboronat** [comment]
Solved!
