### ISSUE TITLE
Option showing with a white text

### ISSUE THREAD

**Issue by felipecastilhos** [ganfra/MaterialSpinner#70]
Hi,

I added the Spinner on my xml as below:

        <fr.ganfra.materialspinner.MaterialSpinner
            android:id="@+id/spinner"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            app:ms_enableErrorLabel="false"
            app:ms_enableFloatingLabel="false"
            app:ms_hint="hint"
            app:ms_floatingLabelColor="#212121"
            app:ms_hintColor="#0000FF" />

But when I add an item on the adapter it always show with a white text. Any ideias how to change the color?

**Comment by muratcanbur** [comment]
@felipecastilhos I suppose You used application context, I would suggest you to use getActivity() if you are in fragment or this if you are in activity
