### ISSUE TITLE
New instance of Material Spinner returns 0 on getSelectedItemPosition()

### ISSUE THREAD

**Issue by peterbetos** [ganfra/MaterialSpinner#71]
It seems that newly created material spinner instance with no selection performed returns getSelectedItemPosition() of 0 instead of -1. Please check why this is occurring. Thanks.

**Comment by lupsyn** [comment]
Same problem here.

**Comment by smtchahal** [comment]
I just made a fork of the project [here](https://github.com/smtchahal/MaterialSpinner) that fixes this issue. I would make a pull request, but it seems this project isn't being maintained anymore.

**Comment by peterbetos** [comment]
Thanks @smtchahal. We're trying to use yours now. Thanks.

**Comment by mdumrauf** [comment]
Hello everyone! We are making this repo to come to live again. @peterbetos please feel free to send any PR you wish :)
