### ISSUE TITLE
Popup is displayed spearted from spinner 

### ISSUE THREAD

**Issue by ahmedmus** [ganfra/MaterialSpinner#76]
here is my CustomDialog.xml
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:minWidth="350dp"
    android:minHeight="200dp">
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_margin="5dp"
        android:orientation="vertical"
        android:background="@color/editTextback">
    <com.jaredrummler.materialspinner.MaterialSpinner
        android:id="@+id/spinner_category"
        app:ms_dropdown_max_height="200dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="20dp"
        android:layout_marginTop="10dp"
        android:layout_marginLeft="10dp"
        android:layout_marginRight="10dp"/>
        <com.jaredrummler.materialspinner.MaterialSpinner
            android:id="@+id/spinner_sub_category"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:layout_marginBottom="5dp"
            android:layout_marginLeft="10dp"
            android:layout_marginRight="10dp"/>
        <Button
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/btn_search"
            android:layout_marginLeft="10dp"
            android:layout_marginRight="10dp"
            android:layout_marginBottom="10dp"
            android:background="@color/white"
            android:text="Search"
            />
   </LinearLayout>
</LinearLayout>`
when the number of items is two the pop up appers spearted from the spnner

**Comment by mdumrauf** [comment]
Wrong MaterialSpinner, Sir! https://github.com/jaredrummler/MaterialSpinner
