### ISSUE TITLE
No support for disabled state.

### ISSUE THREAD

**Issue by drindt** [ganfra/MaterialSpinner#8]
Unfortunately there is no disabled state implemented as suggested in the spec:
http://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field

Thank you for the work.

Maybe it helps to know that:
https://github.com/rengwuxian/MaterialEditText
support this.

**Comment by ganfra** [comment]
I'll add it in the next release

**Comment by carlesferrer** [comment]
+1

**Comment by ganfra** [comment]
Added on 1.1.0
