### ISSUE TITLE
custom font not working

### ISSUE THREAD

**Issue by saibbyweb** [ganfra/MaterialSpinner#81]
Tried to use `app:ms_typeface="typeface.ttf"` to apply custom font to the spinner. But it only applies to the floating label, not to the spinner items.

**Comment by mblancomu** [comment]
Can i access by code to setTypeface?  When are you going to launch another version with this improve? Thanks and great job!

**Comment by joshid** [comment]
You can use this code to set the typeface in spinner values:

`ArrayAdapter<String> adapter = new ArrayAdapter<String>(this,R.layout.simple_spinner_item, items) {

     public View getView(int position, View convertView, ViewGroup parent) {
             View v = super.getView(position, convertView, parent);
             Typeface externalFont=Typeface.createFromAsset(getAssets(), "fonts/your-custom-font.ttf");
             ((TextView) v).setTypeface(externalFont);
             return v;
     }


     public View getDropDownView(int position,  View convertView,  ViewGroup parent) {
              View v =super.getDropDownView(position, convertView, parent);
             Typeface externalFont=Typeface.createFromAsset(getAssets(), "fonts/your-custom-font.ttf");
             ((TextView) v).setTypeface(externalFont);
             return v;
     }`

**Comment by mdumrauf** [comment]
@joshid's answer closes this issue. Thanks guys!
