### ISSUE TITLE
Having MaterialSpinner in a scroller it opens by tapping.

### ISSUE THREAD

**Issue by drindt** [ganfra/MaterialSpinner#9]
I haven't investigated the code, but this behavior is not the proper one. I roughly guess there is a touch event captured in the wrong way.

**Comment by ganfra** [comment]
Ok, thanks for this

**Comment by drindt** [comment]
Should i add a video to better understand my weird english? If i can support you here please let me know.

**Comment by ganfra** [comment]
Should be corrected in the next release ...

**Comment by rocboronat** [comment]
+1 thanks @ganfra

**Comment by Catherine0728** [comment]
Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

To pour the project in, and then make this mistake.

**Comment by mdumrauf** [comment]
Fixed in v1.1.1. Feel free to reopen if necessary.
