### ISSUE TITLE
onSaveInstanceState() not working for MaterialSpinner.

### ISSUE THREAD

**Issue by EzequielMessore** [ganfra/MaterialSpinner#91]
Hello,
When I change the orientation of my screen and save the bundle and restore and use the spinner.setSelection (Obejct) always returns to the default value Select. How can I resolve this?

**Comment by novas1r1** [comment]
+1

**Comment by mdumrauf** [comment]
This might have been an issue with [NineOldAndroids](https://github.com/JakeWharton/NineOldAndroids). In the next milestone we are removing this dependency. I tried what you mentioned and works fine :)
