### ISSUE TITLE
Move hint to right

### ISSUE THREAD

**Issue by nimahedayati** [ganfra/MaterialSpinner#96]
Hi
how i can move hint to right??

**Comment by mdumrauf** [comment]
You can apply `android:gravity="right"` to a custom view set with `app:ms_hintView`

**Comment by rupert2133** [comment]
<?xml version="1.0" encoding="utf-8"?>
<ViewGroup
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_gravity="center">


</ViewGroup>
